server.port=8081
spring.application.name=proxy

spring.data.redis.host=192.168.194.250
spring.data.redis.port=6379
spring.data.redis.timeout=2000

spring.kafka.bootstrap-servers=192.168.194.250:9092
spring.kafka.consumer.group-id=grupo-Matias_Agustin_Perez
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

logging.level.org.springframework.kafka=INFO
logging.level.org.springframework.data.redis=INFO

catedra.url=http://192.168.194.250:8080
catedra.token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwZXJlem1hdGlhcyIsImV4cCI6MTc2NzUyODU3MCwiYXV0aCI6IlJPTEVfVVNFUiIsImlhdCI6MTc2NDkzNjU3MH0.DVyJYKmGYM_b7hoSOhTyWFWokpxVW3ACDpZCh94Wtwi6padwdzYBoVXDDXsWXjkGH7AoIpgyIhntHr7bncmxpw
